# Kestrel-1 CI pipeline configuration

trigger:
- feature/tenantstate
- feature/tenantstate-ci

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
  pool:
    vmImage: $(vmImageName)

  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean package'